language: c

sudo: false

os:
  - linux

sudo: required

compiler:
  - gcc
  - clang

env:
  matrix:
   - CONF="shared"
   - CONF="static"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:ondrej/php'
    packages:
      - gcc-4.9
      - clang
      - openssl
      - libssl-dev

branches:
  only:
    - master

install:
  - wget http://libdill.org/libdill-1.1.tar.gz
  - tar -xzf libdill-1.1.tar.gz
  - pushd libdill-1.1 && ./configure --prefix=/usr && make && sudo make install && popd
  - if [[ $CONF == "shared" ]]; then ./autogen.sh && ./configure --enable-tls && make; fi
  - if [[ $CONF == "static" ]]; then ./autogen.sh && ./configure --enable-tls --disable-shared && make; fi

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
