language: c

sudo: false

os:
  - osx
  - linux

env:
  matrix:
   - CONF="shared"
   - CONF="static"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:ondrej/php'
    packages:
      - gcc-4.9
      - clang
      - openssl
      - libssl-dev

branches:
  only:
    - master

before_install:
  - '[ `type -P brew` ] && brew install openssl --force || ``'
  - export {opt=`pwd`/opt,ssl=/usr/local/Cellar/openssl/1.0.2j}
  - export {CFLAGS=-I$opt/include,LDFLAGS=-L$opt/lib}
  - git clone --depth 1 https://github.com/sustrik/libdill && cd libdill
  - ./autogen.sh && ./configure --prefix=$opt && make && make install
  - cd $opt/lib
  - '[ `type -P brew` ] && for i in $(ls $ssl/lib/lib*); do ln -s $i; done || ``'
  - cd $opt/include
  - '[ `type -P brew` ] && ln -s $ssl/include/openssl || ``'
  - cd ../.. && ./autogen.sh

install:
  - if [[ $CONF == "shared" ]]; then ./configure --prefix=$opt  --enable-tls; fi
  - if [[ $CONF == "static" ]]; then ./configure --prefix=$opt --disable-shared  --enable-tls; fi
  - make

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
